merge into PUBLIC.TRANSACTIONHEADER
using STAGING.TRANSACTIONHEADER_RAW
    on (
        TRANSACTIONHEADER.RECEIPTNUMBER = TRANSACTIONHEADER_RAW.INVOICE_NO
        and TRANSACTIONHEADER.LANENUMBER = TRANSACTIONHEADER_RAW.TILL_NO
        and TRANSACTIONHEADER.STOREIDENTIFIER = TRANSACTIONHEADER_RAW.STORE_CODE
        and TRANSACTIONHEADER.TRANSACTIONDATE = TRANSACTIONHEADER_RAW.INVOICE_DATE
    )
when not matched then
    insert (
        TRANSACTIONDATE,
        STOREIDENTIFIER,
        LANENUMBER,
        RECEIPTNUMBER,
        TRANSACTIONTIME,
        LOYALTYCARDNUMBER,
        CUSTOMERIDENTIFIER,
        TOTALQUANTITYPURCHASED,
        TRANSACTIONNETVALUE
    )
    values (
        TRANSACTIONHEADER_RAW.INVOICE_DATE,
        TRANSACTIONHEADER_RAW.STORE_CODE,
        TRANSACTIONHEADER_RAW.TILL_NO,
        TRANSACTIONHEADER_RAW.INVOICE_NO,
        timestamp_ntz_from_parts(TRANSACTIONHEADER_RAW.INVOICE_DATE, TRANSACTIONHEADER_RAW.SALE_INVC_START_TIME),
        TRANSACTIONHEADER_RAW.LOYALTY_CARD_NO,
        TRANSACTIONHEADER_RAW.CUSTOMER_CODE,
        TRANSACTIONHEADER_RAW.SALE_TOT_QTY,
        TRANSACTIONHEADER_RAW.SALE_NET_VAL
    );
