on: pull_request

jobs:
  check_lint_and_format:
    name: Check for linting and formating
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run Flake8 analysis
        run: |
          python -m flake8 airflow/ rs_airflow/

      - name: Run isort analysis
        run: |
          python -m isort . --check

      - name: Run Black formatter
        run: |
          python -m black --check airflow/ rs_airflow/